export const API_ENDPOINTS = {
  LOGIN: "https://tesoro-backend.onrender.com/api/customer/login/",
  REGISTER: "https://tesoro-backend.onrender.com/api/customer/signup/",

  HOMEPAGE_BANNER: "https://tesoro-backend.onrender.com/api/homepage/banners",
  NEW_ARRIVAL_PRODUCTS: "/api/homepage/new-arrivals",
  RECENTLY_VIEWED: "/api/homepage/recently-viewed-products",
  FLASH_SALE: "/api/homepage/flash-sale",
  TOP_CATEGORIES: "/api/homepage/top-selling-categories",
  OFFER_BANNER: "/api/homepage/offer-banner",
  PRODUCT: "/api/products/product/",
  SMALL_BIZ_STAR: "/api/homepage/founders-pick",
  ORDER: "https://tesoro-backend.onrender.com/api/order/order_id/",
  GUEST_ORDER: "https://tesoro-backend.onrender.com/api/order/guest-order/",
  COLLECTIONS: "http://localhost:5055/api/category/",
  CATEGORIES: "http://localhost:5055/api/category/",
  CATEGORY: "http://localhost:5055/api/category/slug/",
  COLLECTION: "http://localhost:5055/api/categories/slug/",
  PRODUCTS_CATEGORY: "http://localhost:5055/api/products/category/",
  PRODUCTS: "http://localhost:5055/api/products/category/",

  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  FEATURED_CATEGORIES: "/featured_categories.json",
  BRANDS: "/brands.json",
  FEATURED_PRODUCTS: "/featured_products.json",
  TOP_SELLER_PRODUCTS: "/products_top_seller.json",
  ON_SELLING_PRODUCTS: "/products_on_selling.json",
  RELATED_PRODUCTS: "/related_products.json",
  BEST_SELLER_PRODUCTS: "/products_best_seller.json",
  FLASH_SALE_PRODUCTS: "/products_flash_sale.json",
  SEARCH: "/search.json",
  ORDERS: "/orders.json",
};
