export const API_ENDPOINTS = {
  LOGIN: "http://localhost:5055/api/customer/login/",
  REGISTER: "http://localhost:5055/api/customer/signup/",

  HOMEPAGE_BANNER: "https://tesoro-backend.onrender.com/api/homepage/banners",
  NEW_ARRIVAL_PRODUCTS: "/api/homepage/new-arrivals",
  RECENTLY_VIEWED: "/api/homepage/recently-viewed-products",
  FLASH_SALE: "/api/homepage/flash-sale",

  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/categories.json",
  FEATURED_CATEGORIES: "/featured_categories.json",
  COLLECTIONS: "/collections.json",
  BRANDS: "/brands.json",
  PRODUCTS: "/products.json",
  FEATURED_PRODUCTS: "/featured_products.json",
  TOP_SELLER_PRODUCTS: "/products_top_seller.json",
  ON_SELLING_PRODUCTS: "/products_on_selling.json",
  PRODUCT: "http://localhost:5055/api/products/product/",
  RELATED_PRODUCTS: "/related_products.json",
  BEST_SELLER_PRODUCTS: "/products_best_seller.json",
  FLASH_SALE_PRODUCTS: "/products_flash_sale.json",
  SEARCH: "/search.json",
  ORDERS: "/orders.json",
  ORDER: "/order.json",
};
