export const API_ENDPOINTS = {
  LOGIN: "https://tesoro-backend.onrender.com/api/customer/login/",
  REGISTER: "https://tesoro-backend.onrender.com/api/customer/signup/",

  HOMEPAGE_BANNER: "https://tesoro-backend.onrender.com/api/homepage/banners",
  NEW_ARRIVAL_PRODUCTS: "https://tesoro-backend.onrender.com/api/homepage/new-arrivals",
  RECENTLY_VIEWED: "https://tesoro-backend.onrender.com/api/homepage/recently-viewed-products",
  FLASH_SALE: "https://tesoro-backend.onrender.com/api/homepage/flash-sale",
  TOP_CATEGORIES: "https://tesoro-backend.onrender.com/api/homepage/top-selling-categories",
  OFFER_ZONE: "https://tesoro-backend.onrender.com/api/homepage/offer-zone",
  OFFER_BANNER: "https://tesoro-backend.onrender.com/api/homepage/offer-banner",
  PRODUCT: "https://tesoro-backend.onrender.com/api/products/product/",
  SMALL_BIZ_STAR: "https://tesoro-backend.onrender.com/api/homepage/small-biz-stars",
  ORDER: "https://tesoro-backend.onrender.com/api/order/order_id/",
  GUEST_ORDER: "https://tesoro-backend.onrender.com/api/order/guest-order/",
  COLLECTIONS: "https://tesoro-backend.onrender.com/api/category/",
  CATEGORIES: "https://tesoro-backend.onrender.com/api/category/",
  CATEGORY: "https://tesoro-backend.onrender.com/api/category/slug/",
  COLLECTION: "https://tesoro-backend.onrender.com/api/categories/slug/",
  PRODUCTS_CATEGORY: "https://tesoro-backend.onrender.com/api/products/category/",
  PRODUCTS: "https://tesoro-backend.onrender.com/api/products/category/",
  HOMEPAGE_VISIBILITY: "https://tesoro-backend.onrender.com/api/homepage/visibility",
  MYORDER: "https://tesoro-backend.onrender.com/api/order/all",

  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  FEATURED_CATEGORIES: "/featured_categories.json",
  BRANDS: "/brands.json",
  FEATURED_PRODUCTS: "/featured_products.json",
  TOP_SELLER_PRODUCTS: "/products_top_seller.json",
  ON_SELLING_PRODUCTS: "/products_on_selling.json",
  RELATED_PRODUCTS: "/related_products.json",
  BEST_SELLER_PRODUCTS: "/products_best_seller.json",
  FLASH_SALE_PRODUCTS: "/products_flash_sale.json",
  // SEARCH: "http://localhost:5055/api/products/search?search=",
  SEARCH: "https://tesoro-backend.onrender.com/api/products/search?search=",
  ORDERS: "/orders.json",
};
